[[main]]
  name = "Tentang"
  url = "#about"
  weight = 10

[[main]]
  name = "Keahlian"
  url = "#skills"
  weight = 20

[[main]]
  name = "Proyek"
  url = "#projects"
  weight = 30

[[main]]
  name = "Tulisan"
  url = "#posts"
  weight = 40

[[main]]
  name = "Kontak"
  url = "#contact"
  weight = 50

[[main]]
  name = "Database"
  url = "/post/database/"
  weight = 45
